[package]
name = "chimie"
version = "0.1.0"
edition = "2024"

[dependencies]
# actix stuff
actix-files = "0.6.10"
actix-web = "4.13.0"
include_dir = "0.7.4"

# facet stuff
facet = { version = "0.44", features = ["jiff02", "uuid"] }
facet-json = { version = "0.44" }
facet-urlencoded = { version = "0.44" }
facet-actix = { version = "0.44" }
# facet-actix = { path = "../facet-actix" }
facet-error = { version = "0.44" }
figue = { version = "2.0" }

# other
env_logger = "0.11.9"
fjall = "3.0.2"
fjall-typed = { path = "../fjall-typed", features = ["facet_json"] }
actix-multipart = "0.7.2"
tempfile = "3.25.0"
thiserror = "2.0.18"
uuid = { version = "1.21.0", features = ["v7"] }
jiff = "0.2.21"
argon2 = { version = "0.5.3", features = ["zeroize"] }
facet-pretty = "0.43.2"
tokio = { version = "1.49.0", features = ["full"] }
futures-util = "0.3.32"
actix-session = "0.11.0"
time = "0.3.47"
structstruck = "0.5.1"
smart-default = "0.7.1"
actix-ws = { version = "0.4.0", features = ["serde-json"] }
paste = "1.0.15"

[workspace.lints.clippy]
await_holding_refcell_ref = "allow"
